### ISSUE TITLE
Perf

### ISSUE THREAD

**Issue by steveoh** [agrc/bb-econ#17]
It would be interesting to see if there is a noticeable difference in loading the zip, city, and county layers data from "reference" feature layers hidden for the purpose of querying for those values.

Otherwise the <no city> stuff is confusing while the query finishes. I would suggest hiding the div and showing that loading icon or something until _all_ the defers are resolved.

**Comment by stdavis** [comment]
Was it slow for you? Mine is lightening quick after the initial "wake up" to the web api.

**Comment by stdavis** [comment]
Closing this for now.
