### ISSUE TITLE
Current Location refresh

### ISSUE THREAD

**Issue by brigsz** [agrc/bb-econ#18]
Good Morning, If I use the "search by place name" after I do a search by address the current location does not refresh to what I have searched on in the 'search by place name'.  The report generated is for the current location displayed in the current location box in the upper left of the page.
![screen shot 2015-01-02 at 9 24 15 am](https://cloud.githubusercontent.com/assets/6306463/5597553/88cd95d0-9261-11e4-8e7e-cca6a33b2c54.png)

**Comment by brigsz** [comment]
I believe that the query string parameters are x:426754.86846242094
y:4514922.104177411
f:json
I believe that is the parameters of the point, of 717 11th ave and not the centroid of Sen 13.  Or is this even a valid search?  Should we allow users to return BB results from a magic zoom

**Comment by brigsz** [comment]
Yes, I am convinced that the system does not allow a report to be generated if a user utilizes the magic zoom to get to an area.   They must geocode or click on the map.

Thanks, yours truly,
Reza

**Comment by stdavis** [comment]
Yes, that's correct. The magic zoom returns a polygon. We could get the centroid and generate a report based on that. I didn't see anything in the specs about generating a report from the magic zoom location but I certainly could have missed it.

**Comment by brigsz** [comment]
Yes, I don't remember anything in the specs either, so I think we are fine.  I was just fooling with the app and just noticed that.

**Comment by stdavis** [comment]
OK. Closing for now.
