### ISSUE TITLE
Open report in a new tab

### ISSUE THREAD

**Issue by stdavis** [agrc/bb-econ#21]

**Comment by stdavis** [comment]
@jpechmann How big of a deal is this? I didn't see the in the original specs so I asked @steveoh for input and we came up with a decision on our own. I should have asked you for clarity.

This isn't a huge thing but would take some significant effort. Just wondering where in the priorities it should fall. 

One possibly nice side effect from making this change is that we could create sharable report URL's by including the location coordinates in the URL as parameters. So after generating a report you could just copy the URL and send it to someone else and they would see the same report.

**Comment by jpechmann** [comment]
I think the original requirement is this one "As a user, I’d like to be able to generate a location summary report in a new tab based on the current chosen location." 
But.. that being said, would it be easier to allow a user to right mouse click on the "Get Summary" button and have the option to open in a new tab? That option isn't currently there.

**Comment by stdavis** [comment]
You got me. I don't remember why I even thought that it was an option given that requirement. My bad.

No, it would be more work to allow for both options. I'll work on getting the new tab option working and trash the single window solution.
