### ISSUE TITLE
Change symbology/text on railroads

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#25]
Make railroad symbology thicker so it stands out more. Also make it the same blue color. Change the text of "Railroads" to "Heavy Rail". When I get ArcMap I'll check to see if there needs to be a query on the railroads in the SGID. I suspect there needs to be.

**Comment by stdavis** [comment]
@jpechmann Is it `TYPE = 'Heavy'`?

**Comment by jpechmann** [comment]
Yes! Looks like it is. Thanks.
