### ISSUE TITLE
Change park icons and organization under Lifestyle

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#26]
Put State Parks in a different checkbox category than National Parks and National Monuments. Aaron will send new logos also.

**Comment by stdavis** [comment]
@jpechmann What query do I use to separate this data into state and national parks/momuments? Or are there separate datasets somewhere? I looked quickly in SGID and didn't see anything but may have missed it.

**Comment by ZachBeck** [comment]
The TYPE field in ParksAndMonuments will separate state parks, natl parks, natl monuments, and natl rec areas.

**Comment by stdavis** [comment]
I'm a dope. I had that field turned off in my mxd. Thanks @ZachBeck.
