### ISSUE TITLE
Change text under Utilities

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#28]
Change "Telephone Service Areas" on map and report to "Local Exchange Areas" (polygons denote service areas, not actual service).

Change  "Electrical" to "Electric Utility" on report and "Electric Provider" on map.

Change Natural Gas Service's return on report to say "Questar Gas" with website (https://www.questargas.com/) for "yes", and for "no" return "Unknown"

**Comment by jpechmann** [comment]
Kelleigh now wants "Electric Utility Territory". Sorry about that.

**Comment by stdavis** [comment]
Final word from @jpechmann is "Electric Utility Territory" for both map and report. So let it be written...
