### ISSUE TITLE
Change Utilities to radio button

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#30]
Change the options under Utilities on the map to a radio button, not a checklist. I think if you do that you need to add an option that says "None" if you don't want any utilities drawn.

**Comment by stdavis** [comment]
Do we really need a "None" option? Can't the user just toggle the section by clicking on the header and the layer will turn off?

**Comment by jpechmann** [comment]
Oh, if that works, then yes. That sounds better.
