### ISSUE TITLE
Re-design address/place locator search boxes

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#33]
Aaron will get screenshots(?) to you on Monday 1/12/15. The basic feedback is to condense the location tools.

**Comment by jpechmann** [comment]
From what I gather, Aaron isn't going to send us anything else. I know we talked a little about the changes on this a little bit, but feel free to clarify with me tomorrow.

**Comment by jpechmann** [comment]
To condense the address/place locator boxes, GOED wanted to combine the search by place name box and zip or city box. Then, if only a city or zip was entered, without an address, the zoom locations in the SGID would be used as the locator. If a full address was entered, the AGRC geocoder would be used. 

Change "Find Address" to "Find Location"

They also wanted to put the "address" and "zip or city" text in the text box, like the "search by place name.." box is now. If that's a deal breaker though, I wouldn't do it.

**Comment by brigsz** [comment]
okay, a single search box for all location searches whether it is an address search, a city search, a zip code search or a placename search.  Is that correct?

**Comment by jpechmann** [comment]
Two search boxes. One for address, one for place names. If only the place name box is filled out, the zoom locations locator is used, not the geocoder. Does that make sense?
