### ISSUE TITLE
Add SureSites/User Assistance Links

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#34]
Link to SureSites (http://utahsuresites.com/) in prominent place. 

Add contact information somewhere to contact Kelleigh if a user wants assistance with site selection. I discussed this one with Aaron for awhile, he's going to get us ideas on the design of that.

**Comment by jpechmann** [comment]
Same thing, from what I gather, Aaron isn't going to send us anything else.

**Comment by stdavis** [comment]
Closed with 805e278190c84249cb9709e87479de4f4e44d9ac
