### ISSUE TITLE
Roads filter

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#36]
Change roads filter in report to CARTOCODE in ( '1', '2', '3', '4', '5')

**Comment by jpechmann** [comment]
Dropping cartocode 8 was supposed to drop off minor roads, especially in the Salt Lake valley (2700 W, 100 N, etc), but it doesn't seem to have worked in the latest push. Thoughts? Also, I totally forgot to add pull the name from "HWYNAME". Sorry about that.

**Comment by stdavis** [comment]
Try it now. I think that I screwed up copying the config file for the gp task to the server.
