### ISSUE TITLE
Demographic layers

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#43]
Add demographic layers to report when they are ready from Mike.

**Comment by stdavis** [comment]
On the spreadsheet I see these categories that I think are demographic related: Age, Higher Education Level, Average Wage, Average Household Income & Top Industries in county.

Mike's data has: Average monthly income, Average household income and the top 10 industries in county. Should I be waiting for more data from Mike or did you decide not to do the other layers?

**Comment by jpechmann** [comment]
@ZachBeck should have gotten that data (Age and Higher Education Level) from Josh to add to the data used for this app. Zach do you know where that is still?

**Comment by ZachBeck** [comment]
I:\PROJECTS\Broadband\Box\Census_Data.gdb\UT_Cnty_demographics
