### ISSUE TITLE
"i" button for utility layers

### ISSUE THREAD

**Issue by stdavis** [agrc/bb-econ#51]
Waiting on @bgranberg for text.

**Comment by BGranberg** [comment]
Short Order area - typically 60 days or less
Custom Order area - typically 9 months or less

**Comment by stdavis** [comment]
@jpechmann Do you remember what the deal is on this issue? Is this a single "i" button for the utilities group or for an individual layer?

**Comment by jpechmann** [comment]
@BGranberg this requirement came from this note from your meeting with K Cole "utilities 'i' text with each utility layer: explain territory vs service area…boundaries shown, service not guaranteed for full territory, provider will show up in report...Bert can write text"

I think the idea was an "i" button for every layer under Utilities.

**Comment by brigsz** [comment]
Who actually has the text that should go with each utility layer?  Is it unique to each layer?

**Comment by BGranberg** [comment]
Approximate service area the natural gas distribution network in Utah

Jurisdictional boundaries for Utah's culinary water districts. The location
report provides show the district name.

Jurisdictional boundaries for Utah's electricity providers. The location
report provides show the district name.

Territory boundaries for Utah's incumbent telephone providers. The location
report provides show the provider name.

On Tue, Jan 27, 2015 at 12:10 PM, Matt Peters <notifications@github.com>
wrote:

> Who actually has the text that should go with each utility layer? Is it
> unique to each layer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/bb-econ/issues/51#issuecomment-71707870>.
>



-- 
Bert Granberg, Director
Utah Automated Geographic Reference Center (AGRC)
1 State Office Bldg, Rm 5130
Salt Lake City, UT 84114
bgranberg@utah.gov
801 538-3163 (o)
801 558 3563 (m)
