### ISSUE TITLE
Regional Airport Symbols

### ISSUE THREAD

**Issue by stdavis** [agrc/bb-econ#52]
FAA abrevs to SGU (StGeorge), CDC (Cedar), PVU (provo), VEL (vernal), CYN (Moab), OGD (ogden)

**Comment by brigsz** [comment]
Do these abbreviations need to be seen in the pop up when a user clicks on an airport?

**Comment by stdavis** [comment]
I believe that these are abbreviations that are to show up in the symbol markers for the airports. In a similar fashion to the Salt Lake City airport marker. 

-Scott

**Comment by stdavis** [comment]
This will take some rewriting of code. I would have written the code differently if I knew that this was a requirement from the beginning.

**Comment by stdavis** [comment]
@jpechmann Is this still valid?

**Comment by jpechmann** [comment]
I'll check with Kelleigh but leave it as the lowest priority for now.
