### ISSUE TITLE
Sure Sites/Ask Expert section in footer

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#60]
Remove Sure Sites/Ask Expert section from footer.

**Comment by stdavis** [comment]
Closed earlier today with 82aad68. Over site on my part. Thanks for the tip!

**Comment by jpechmann** [comment]
Oops! Sorry. I didn't see that either. Thanks Scott!

**Comment by stdavis** [comment]
No worries. I didn't expect you to see that commit since i didn't open a related issue.
