### ISSUE TITLE
Link header to homepage 

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#61]
Link the header icon to the homepage. This only impacts the report I think.

**Comment by stdavis** [comment]
So link it to locate.utah.gov? Just want to be sure.

On Thu, Feb 5, 2015 at 9:22 AM, jpechmann <notifications@github.com> wrote:

> Link the header icon to the homepage. This only impacts the report I
> think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/bb-econ/issues/61>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by jpechmann** [comment]
Yup.
