### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#62]
Aaron and I have been getting the error "There was an error generating the report!" when generating a report today.

**Comment by steveoh** [comment]
@jpechmann can you provide useful information to help figure out the problem. Like, browser, which area you are generating the report for, are there any patterns for the area or is it failing on everything...

**Comment by jpechmann** [comment]
So.. it just started working again. Aaron said he tried twice in West Jordan sometime before 9:30am, and I tried once in Salt Lake County to confirm it wasn't working. We were both in chrome. But, it's working now again, so I'm not sure what was up. I'll close this for now but check on it periodically to see if I can reproduce it.

**Comment by stdavis** [comment]
The most helpful info would be the url of the report that generates the
error.

Thanks!

On Thu, Feb 5, 2015 at 9:46 AM, jpechmann <notifications@github.com> wrote:

> So.. it just started working again. Aaron said he tried twice in West
> Jordan sometime before 9:30am, and I tried once in Salt Lake County to
> confirm it wasn't working. We were both in chrome. But, it's working now
> again, so I'm not sure what was up. I'll close this for now but check on it
> periodically to see if I can reproduce it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/bb-econ/issues/62#issuecomment-73080299>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>
