### ISSUE TITLE
Rollup menu icon/functionality

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#64]
Add a "hamburger" option to rollup menu items in the right side toolbar.

**Comment by stdavis** [comment]
@jpechmann Where's the hamburger icon supposed to go? In the "Current Location" box?

**Comment by jpechmann** [comment]
Aaron says upper left. Directly from him-

 it should only appear when less than say 600-650 pixels (mobile devices.  the entire menu gets rolled up to the top.  resize the window on this site and you'll see what i am talking about.

http://lonepeak.utah.gov/

**Comment by stdavis** [comment]
@jpechmann This has also been pushed to the test server. Check it out and let me know if there are changes that need to be made or if I can push these changes as v1.1.0 to production.
