### ISSUE TITLE
Map full screen, frozen top and bottom bars

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#67]
From Kelleigh - freeze top header so when a user scrolls down on the map, the top header is always visible.

**Comment by jpechmann** [comment]
This is only a low priority if it's not a quick fix.

**Comment by jpechmann** [comment]
Kelleigh mentioned this again on 3/2/2015. After discussion we decided this should involve making the map fullscreen, freezing the top and bottom bars, and adding a scroll to the accordion side menu.

**Comment by stdavis** [comment]
@jpechmann I just pushed the full screen branch to http://test.mapserv.utah.gov/bb-econ/. Would you mind taking a look and seeing if it's what you want?

**Comment by jpechmann** [comment]
This looks so great! Kelleigh loves the new side bar. Two things.

1. Can you enable mouse zooming?
2. Right now when you collapse a category it turns off all those layers on the map. Can you just remove that ability on the category? So nothing will be turned on or off on the map when you click on the category.

Thanks!

**Comment by stdavis** [comment]
Just pushed these two items.
