### ISSUE TITLE
Columns in report

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#69]
Kelleigh would like the columns in the report lined up the best they can be.

**Comment by jpechmann** [comment]
Re-opening this issue in case it is possible to improve alignment.

**Comment by stdavis** [comment]
What, specifically needs to be improved?

On Mon, Mar 9, 2015 at 2:28 PM, jpechmann <notifications@github.com> wrote:

> Re-opening this issue in case it is possible to improve alignment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/bb-econ/issues/69#issuecomment-77935192>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by jpechmann** [comment]
The contact name, contact phone, and contact email are all slightly off.

**Comment by jpechmann** [comment]
Okay, Kelleigh has a new request for the columns. She wants the broadband columns re-ordered as follows in hopes it'll help with the alignment. 

Fiber Providers: Provider, Website, Phone Number, Contact Name, Contact Email, Providing Fiber in:,
Other Fixed Broadband Providers: Provider, Website, Phone Number (the remaining columns would be empty with no headers or other content)

**Comment by jpechmann** [comment]
Sorry, I probably explained this poorly. Kelleigh doesn't want the Contact Name or Contact Email under "other fixed broadband providers". So no header text, and no values in the rows. Other than that everything looks great

**Comment by stdavis** [comment]
@jpechmann Thanks for catching this. You were clear in the original message. I just didn't read it correctly. Fix is coming shortly.
