### ISSUE TITLE
Text under "ask an expert!"

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#72]
Change text in the pop-up from "Ask An Expert!".  Waiting on Kelleigh for exact text but it'll be similar to-

Technical Questions: (801) 538-8831
Site Selector:  (801) XXX-XXXX

**Comment by stdavis** [comment]
@jpechmann Did you ever get the exact text for this?

**Comment by jpechmann** [comment]
Nope. I will ask her right now.

**Comment by jpechmann** [comment]
Technical Questions: (801) 538-8831
Economic Development Assistance: (801) 328-8839
