### ISSUE TITLE
New logo for application

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#73]
Attached is the logo Kelleigh wants swapped out for the main logo in the upper left of the application. 
![locate logo horizontal](https://cloud.githubusercontent.com/assets/8332142/6830230/12961bcc-d2de-11e4-9404-47797cace075.png)

**Comment by stdavis** [comment]
@jpechmann Do you have a vector version of this file? Something like an `.svg`?

**Comment by stdavis** [comment]
The ones that Kelleigh sent should work.

**Comment by stdavis** [comment]
![image](https://cloud.githubusercontent.com/assets/1326248/7006670/36c767ba-dc40-11e4-9dac-c0e4fd4a3e2d.png)
