### ISSUE TITLE
Application Analytics

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#74]
Kelleigh would like to track analytics on the following:

1. Number and locations of users (already being tracked) 
2. Views per map layer (how many times each layer is turned on)
3. How many reports are being generated total and how many users are generating reports (reports per user)
4. Where (xy or address) are reports are being generated (I suspect this might already be being tracked through our apis?)
5. Where users are connecting that are generating the report 

If you think there is anything else worth tracking go for it. Thanks!

**Comment by steveoh** [comment]
hey @stdavis check out https://github.com/yeoman/insight

**Comment by stdavis** [comment]
https://developers.google.com/analytics/devguides/collection/analyticsjs/events#crossbrowser

**Comment by stdavis** [comment]
@jpechmann I think that I have all of this data being tracked through analytics. Let me know when you have some time and I'd like to go through it with you.

**Comment by stdavis** [comment]
Closed with 843ba81138eedf47c43af75ab0cdeed487570b93
