### ISSUE TITLE
Senawave shows up multiple times in reports

### ISSUE THREAD

**Issue by stdavis** [agrc/bb-econ#80]

**Comment by stdavis** [comment]
@jpechmann Check out OBJECTID's `1100` & `1101` in `UBBMAP.UBBADMIN.BB_Service_Wireless`. Are they duplicates?

**Comment by jpechmann** [comment]
No, one is residential service and the other is commercial service. The commercial has faster speeds.

**Comment by stdavis** [comment]
I'm assuming that this is why Kelleigh is seeing duplicate Senica entries.
Am I supposed to be removing duplicate businesses in the report? I don't
believe that it does this currently.

On Mon, Apr 20, 2015 at 5:04 PM, jpechmann <notifications@github.com> wrote:

> No, one is residential service and the other is commercial service. The
> commercial has faster speeds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/bb-econ/issues/80#issuecomment-94588382>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by jpechmann** [comment]
I think maybe it doesn't check for duplicates in wireless, but it does in wireline? I checked an area I know has residential and business for wireline (Emery Telcom in Castle Dale) and it doesn't duplicate Emery in the report under other fixed providers.

**Comment by stdavis** [comment]
@jpechmann: So I should be removing duplicate providers between the "Fiber" and "Other Fixed Broadband" lists? If they show up in "Fiber" then they should be removed from "Other"?

For example, check out [this report](http://locate.utah.gov/report.html?x=425065.11760025565&y=4512322.68057195&address=112%20E%20500%20S&city=Salt%20Lake%20City&zip=84111&county=Salt%20Lake). SenaWave, Syringa Networks, and XO Communications should be removed from "Other"?

**Comment by jpechmann** [comment]
There can be duplicates between "Fiber" and "Other Fixed", I think the issue was that SenaWave was listed twice under "Other Fixed". Although I just ran this report and its listed three times under Fiber- http://locate.utah.gov/report.html?x=425017.3444575727&y=4512504.2185141295&address=424%20S%20State%20St&city=Salt%20Lake%20City&zip=84111&county=Salt%20Lake. So.. I think you just need to double check for duplicates within each list.

**Comment by stdavis** [comment]
Only "other" providers were being filtered for duplicates. I added a duplicate filter for fiber now as well.
