### ISSUE TITLE
No hamburger for landscape iphone 5

### ISSUE THREAD

**Issue by stdavis** [agrc/bb-econ#81]

**Comment by amcelwee** [comment]
The map and hamburger menu cannot be accessed in landscape view.  

Footers: I would remove both footers.  If you have to keep the sure sites and ask an expert references on the home page, I would turn them into text links.  You could also put them into the hamburger menu as well.  

Location Summary: You could either shrink the size of the location summary or remove it and only show it once an address has been identified.  The user could then close it when they want to perform another search.
