### ISSUE TITLE
Identify/Label polygons

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#82]
Allow for a user to view or determine polygon labels where appropriate (see list below). Right now the only way to determine the polygon labels is to run a report. We need a way for the user to view the polygon labels on the map viewer. This could either be an identify, or labels show up at some scale, or something else.

Electric Utility Territory
Local Exchange Areas
Culinary Water
Enterprise Zones

**Comment by stdavis** [comment]
@jpechmann I pushed a new update to test.mapserv.utah.gov/bb-econ that includes scale dependent labels for these layers. Can you take a look and let me know what you think?

**Comment by jpechmann** [comment]
I forwarded this to Bert and Kelleigh, I'll report back. Thanks!

**Comment by jpechmann** [comment]
Kelleigh said it looks good. I think we can close.
