### ISSUE TITLE
www.locate.utah.gov

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#83]
@brigsz  Is it possible to have www.locate.utah.gov point to locate.utah.gov?

**Comment by steveoh** [comment]
ask joe benson to do that at the f5 level

**Comment by stdavis** [comment]
This is working now. I assume that @brigsz made it happen?

**Comment by brigsz** [comment]
Yes, I had the alias registered in DNS



On May 12, 2015, at 8:52 AM, Scott Davis <notifications@github.com> wrote:

This is working now. I assume that @brigsz <https://github.com/brigsz> made
it happen?

—
Reply to this email directly or view it on GitHub
<https://github.com/agrc/bb-econ/issues/83#issuecomment-101307712>.
