### ISSUE TITLE
Link to broadband.utah.gov

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#84]
Kelleigh would like to link to broadband.utah.gov somewhere along the top. @stdavis , is it possible to link just the text in the logo "Broadband Outreach Center" and the state icon to broadband.utah.gov?

**Comment by stdavis** [comment]
Right now that's all one image with the logo. But I can chop it up and
convert the text to real text on the page and link them. I will just take
some work.

On Wed, Apr 29, 2015 at 4:28 PM, jpechmann <notifications@github.com> wrote:

> Kelleigh would like to link to broadband.utah.gov somewhere along the
> top. @stdavis <https://github.com/stdavis> , is it possible to link just
> the text in the logo "Broadband Outreach Center" and the state icon to
> broadband.utah.gov?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/bb-econ/issues/84>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by jpechmann** [comment]
Hmm. I think that will be better than linking a logo that says another website. What do you think?

**Comment by stdavis** [comment]
For sure we shouldn't link an image that says "LOCATE.UTAH.GOV" to another
website.

On Thu, Apr 30, 2015 at 8:59 AM, jpechmann <notifications@github.com> wrote:

> Hmm. I think that will be better than linking a logo that says another
> website. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/bb-econ/issues/84#issuecomment-97828729>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by stdavis** [comment]
@jpechmann Is Kelleigh still wanting this changed to something else or is she happy with the way it is currently?

**Comment by jpechmann** [comment]
Kelleigh still wants a better solution. I'm going to try and work with Amie Hughes/Aaron to figure something out. Thanks for the reminder!

**Comment by jpechmann** [comment]
Update. We discussed some options with Kelleigh that she likes. Aaron is going to make some screenshots.
