### ISSUE TITLE
Enterprise Zones

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#89]
Add Enterprise Zone data to application.

**Comment by jpechmann** [comment]
From Kelleigh: "I think we should do the four color strategy and label them by the city/county they correspond with." I think @ZachBeck created the 4 color strategy in the data. Maybe for now we should just put them in as all one color?

**Comment by stdavis** [comment]
Waiting on new data to be pushed to SGID.

**Comment by stdavis** [comment]
OK. Enterprise zones are enabled in test. You can check them out here: http://test.mapserv.utah.gov/bb-econ/#x=624938&y=4476541&scale=288895&l=0%2C1&l=2%2C3%2C4&l=999&l=19

Also take a look at a report with them on it: http://test.mapserv.utah.gov/bb-econ/report.html?x=623638.9624565082&y=4478910.144582822&address=730%20W%20250%20S&city=Vernal&zip=84078&county=Uintah

Let me know if I need to make any changes or if I can push to production.

**Comment by jpechmann** [comment]
Okay, Enterprise Zones has been updated in SGID10. Also, Bert would like the order changed under Workforce.

On Map: Enterprise Zones above Higher Education Schools
On Report (top down): Enterprise Zones, Top 10 County Industries, County Demographics, Higher Education Schools.

Come find me if that doesn't make sense. Thanks Scott!

**Comment by stdavis** [comment]
@jpechmann This has been pushed to production.
