### ISSUE TITLE
15 Minute Drive Tims

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#91]
Kelleigh wants all drive times in 15 minute intervals. The drop off times (the max amount of time) for each category can stay the same.

**Comment by stdavis** [comment]
This data has been pushed to production and everything seems to be working.

@jpechmann I noticed that Zach generated hospital drive times. However, they are not in the report. Are they supposed to be there? Did I miss a requirement somewhere for them?

**Comment by stdavis** [comment]
Closing for now...
